// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WC26Pool.API.Data;

#nullable disable

namespace WC26Pool.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623174322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WC26Pool.API.Models.DayPredictionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("HasSubmittedAll")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("Date", "ParticipantId")
                        .IsUnique();

                    b.ToTable("DayPredictionOrders");
                });

            modelBuilder.Entity("WC26Pool.API.Models.DayVisibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("ForceRevealedByAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DayVisibilities");
                });

            modelBuilder.Entity("WC26Pool.API.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AwayTeamFlag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeTeamFlag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PointsCalculated")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("WC26Pool.API.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = false,
                            Name = "Pedro",
                            TotalPoints = 0
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            Name = "Gabriel",
                            TotalPoints = 0
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = false,
                            Name = "Vinícius",
                            TotalPoints = 0
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            Name = "João",
                            TotalPoints = 0
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = false,
                            Name = "Guilherme",
                            TotalPoints = 0
                        },
                        new
                        {
                            Id = 6,
                            IsAdmin = true,
                            Name = "Eder",
                            TotalPoints = 0
                        });
                });

            modelBuilder.Entity("WC26Pool.API.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<int?>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("PredictedAwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("PredictedHomeScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("ParticipantId", "MatchId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("WC26Pool.API.Models.DayPredictionOrder", b =>
                {
                    b.HasOne("WC26Pool.API.Models.Participant", "Participant")
                        .WithMany("DayPredictionOrders")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WC26Pool.API.Models.Prediction", b =>
                {
                    b.HasOne("WC26Pool.API.Models.Match", "Match")
                        .WithMany("Predictions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WC26Pool.API.Models.Participant", "Participant")
                        .WithMany("Predictions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WC26Pool.API.Models.Match", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("WC26Pool.API.Models.Participant", b =>
                {
                    b.Navigation("DayPredictionOrders");

                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
